version: '3'
networks:
 campus_virtual:

services:
   ud-observatorio-user:
     build: .
     container_name: ud-observatorio-use
     restart: on-failure
     env_file:
        - .env
     ports:
        - "3020:3020"   
     networks:
        - campus_virtual          

networks:
  campus_virtual:
    external: true
